version: '3'

services:
  testbed:
    build: portfoliowebsite
    image: testbed
    container_name: testbed
    ports: 
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 portfoliowebsite.wsgi
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.testbed.rule=Host(`michalina-czechowska.pl`)"
      - "traefik.http.routers.testbed.tls=true"


  reverse-proxy:
    image: traefik:latest
    container_name: reverse-proxy
    command:
     - --entrypoints.web.address=:80
     - --entrypoints.web-secure.address=:443
     - --providers.docker=true
     - --providers.file.directory=/etc/traefik/config/
     - --providers.file.watch=true
     - --api.insecure
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./reverse-proxy/certificates.toml:/etc/traefik/config/certificates.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt/live/michalina-czechowska.pl/cert.pem:/etc/certs/cert.pem:ro
      - /etc/letsencrypt/live/michalina-czechowska.pl/chain.pem:/etc/certs/chain.pem:ro
      - /etc/letsencrypt/live/michalina-czechowska.pl/fullchain.pem:/etc/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/michalina-czechowska.pl/privkey.pem:/etc/certs/privkey.pem:ro
    restart: on-failure

  nginx:  # nginx to serve static files
    image: nginx:1.15-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./portfoliowebsite/static:/static
    labels:  # route defined to handle specific rule and enabling tls certresolver
      - "traefik.enable=true"
#       - "traefik.http.routers.static-http.entrypoints=websecure"
      - "traefik.http.routers.static.tls=true"
      - "traefik.http.routers.static.rule=Host(`michalina-czechowska.pl`) && PathPrefix(`/static`)" 